version: '3'

services:
  traefik:
    image: traefik:v2.10.4
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NAMECHEAP_API_USER=cctechwiz
      - NAMECHEAP_API_KEY_FILE=/run/secrets/namecheap_api_key
    networks:
      - backbone
    restart: unless-stopped

networks:
  backbone:
    external: true


secrets:
  namecheap_api_key:
    external: true
