---
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    ports:
      - 3001:3001
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - backbone
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma.rule=Host(`status.cosmere.cctechwiz.com`)
      - traefik.http.routers.uptime-kuma.entrypoints=websecure
      - traefik.http.routers.uptime-kuma.tls=true
      - traefik.http.routers.uptime-kuma.tls.certresolver=staging

networks:
  backbone:
    external: true

volumes:
  uptime-kuma-data:
    driver: local
