---
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    ports:
      - 3001:3001
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - backbone
    labels:
      - traefik.enable=true
      - traefik.docker.network=backbone
      - traefik.http.routers.uptime-kuma-http.rule=Host(`status.cosmere.cctechwiz.com`)
      - traefik.http.routers.uptime-kuma-http.entrypoints=web
      - traefik.http.routers.uptime-kuma-http.middlewares=https-redirect
      - traefik.http.routers.uptime-kuma-https.rule=Host(`status.cosmere.cctechwiz.com`)
      - traefik.http.routers.uptime-kuma-https.entrypoints=websecure
      - traefik.http.routers.uptime-kuma-https.tls=true
      - traefik.http.routers.uptime-kuma-https.tls.certresolver=staging

networks:
  backbone:
    external: true

volumes:
  uptime-kuma-data:
    driver: local
